name: dart_cv
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.4.3

dependencies:
  path: any
  yaml: any
  xml: any
  pdf: any
  json_annotation: ^4.9.0

dev_dependencies:
  pedantic: ^1.8.0
  json_serializable: any
  build_runner: any